paths:
  route_name: osdpm_0_3 # 指定routes下的文件夹名
  #osdpm_0_3 osdpm_0_2 osdpm_0_5 osdpm_4_1
  store_path: outputs/

params:
  heuristic: dijkstra
  heuristic_f: my_weight
  multi_job: True
  time_limit: 120  # 单位：秒
