paths:
  route_name: osdpm_3_1 # 指定routes下的文件夹名
  #osdpm_0_3 osdpm_0_2 osdpm_0_5
  store_path: outputs/

params:
  heuristic: dijkstra
  heuristic_f: my_weight
  multi_job: True
  n_perturbation: 50
  operator_p: [0.15, 0.15, 0.15, 0.15, 0.4]
  gen_num: 10000
  lagrangian_lambda: 2000
  time_limit: 120  # 单位：秒
  show_sub_problem: False  # 是否展示sub_problem可视化
